language: android
sudo: false
jdk: oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;28.0.3"
android:
    components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-27
        - extra-android-m2repository
env:
    - TERM=dumb
script:
    - cd CongressRoutePlanner
    - ./gradlew checkDebug lintDebug
cache:
    directories:
        - $HOME/.gradle
