language: android
sudo: false
jdk: oraclejdk8
before_install:
  - yes | sdkmanager "platforms;build-tools-26.0.2;android-27"
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-27
        - extra-android-m2repository
env:
    - TERM=dumb
script:
    - cd CongressRoutePlanner
    - ./gradlew checkDebug lintDebug
cache:
    directories:
        - $HOME/.gradle
